services:
  # Service frontend
  frontend:
    build:
      dockerfile: Dockerfile
    container_name: app_frontend
    restart: unless-stopped
    # env_file: .env
    ports:
      - "4321:4321"
    environment:
      - VIRTUAL_HOST=www.xoailac.top
      - LETSENCRYPT_HOST=www.xoailac.top
      - LETSENCRYPT_EMAIL=ml2673572@gmail.com
      - VIRTUAL_PORT=4321
    networks:
      - app-network
networks:
  app-network:
    external: true
    name: app-network
