services:
  # Service frontend
  frontend:
    build:
      dockerfile: Dockerfile
    container_name: app_frontend
    restart: unless-stopped
    # env_file: .env
    ports:
      - "4321:4321"
    networks:
      - app-network
networks:
  app-network:
    external: true
    name: app-network
