name: CI/CD for Astro App

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: List directory contents
        run: ls -la
        # Helps debug if package-lock.json is present

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci
        # npm ci ensures a clean install using package-lock.json

      - name: 🔨 Build
        run: npm run build

      - name: 🧪 Astro Check
        run: npm run astro check
        # If your package.json defines test:check-examples, use:
        # run: npm run test:check-examples

      - name: Upload logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: |
            dist/
            *.log
          retention-days: 7
      - name: 🚀 Deploy to VPS
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            echo "🔄 Pulling latest code ..."
            cd /home/${{secrets.HOME_USER}}/movie28/28movie.frontend
            git reset --hard
            git pull origin main
            echo "🐳 Restarting Docker ontainers...."
            docker compose build
            docker compose up -d --remove-orphans
            echo "✅ Deploy complete!"
      - name: 📢 Notify to Telegram
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage \
          -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
          -d parse_mode=Markdown \
          -d text="✅ *Deploy thành công!* \nRepo: \`${{ github.repository }}\`\nBranch: \`${{ github.ref_name }}\`\nCommit: [${{ github.sha }}](${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }})"
